//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoInsurance.Web.ATMStagsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATMStagsReference.ATMStagsSoap")]
    public interface ATMStagsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Debitar", ReplyAction="*")]
        void Debitar(int value, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Debitar", ReplyAction="*")]
        System.Threading.Tasks.Task DebitarAsync(int value, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ATMStagsSoapChannel : AutoInsurance.Web.ATMStagsReference.ATMStagsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATMStagsSoapClient : System.ServiceModel.ClientBase<AutoInsurance.Web.ATMStagsReference.ATMStagsSoap>, AutoInsurance.Web.ATMStagsReference.ATMStagsSoap {
        
        public ATMStagsSoapClient() {
        }
        
        public ATMStagsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATMStagsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMStagsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMStagsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Debitar(int value, int id) {
            base.Channel.Debitar(value, id);
        }
        
        public System.Threading.Tasks.Task DebitarAsync(int value, int id) {
            return base.Channel.DebitarAsync(value, id);
        }
    }
}
